name: parmesan
description: "CLI tool to scaffold Flutter + C++ FFI projects"
version: 0.1.0
repository: https://github.com/invok3/parmesan

environment:
  sdk: ^3.11.5

dependencies:
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  test: ^1.31.1
  lints: ^6.1.0

executables:
  parmesan:
